Import 3.3-1.0 release

diff --git a/uclinux-rootfs/user/xfsprogs/include/buildrules b/uclinux-rootfs/user/xfsprogs/include/buildrules
--- a/uclinux-rootfs/user/xfsprogs/include/buildrules
+++ b/uclinux-rootfs/user/xfsprogs/include/buildrules
@@ -1,42 +1,38 @@
 #
 # Copyright (c) 1999, 2001-2003 Silicon Graphics, Inc.  All Rights Reserved.
 #
-# This program is free software; you can redistribute it and/or modify it
-# under the terms of version 2 of the GNU General Public License as published
-# by the Free Software Fondation.
-#
-# This program is distributed in the hope that it would be useful, but WITHOUT
-# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
-# FITNESS FOR A PARTICULAR PURPOSE.  Further, any license provided herein,
-# whether implied or otherwise, is limited to this program in accordance with
-# the express provisions of the GNU General Public License.  Patent licenses,
-# if any, provided herein do not apply to combinations of this program with
-# other product or programs, or any other product whatsoever.  This program is
-# distributed without any warranty that the program is delivered free of the
-# rightful claim of any third person by way of infringement or the like.  See
-# the GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License along with
-# this program; if not, write the Free Software Foundation, Inc., 59 Temple
-# Place - Suite 330, Boston MA 02111-1307, USA.
-# Common build rules for gmake
-#
 ifndef _BUILDRULES_INCLUDED_
 _BUILDRULES_INCLUDED_ = 1
 
 include $(TOPDIR)/include/builddefs
 
-clean clobber : $(SUBDIRS)
-	rm -f $(DIRT)
-	@rm -fr .libs
-	$(SUBDIRS_MAKERULE)
+clean clobber : $(addsuffix -clean,$(SUBDIRS))
+	@rm -f $(DIRT) .ltdep .dep
+	@rm -fr $(DIRDIRT)
+%-clean:
+	@echo "Cleaning $*"
+	$(Q)$(MAKE) $(MAKEOPTS) -C $* clean
 
 # Never blow away subdirs
 ifdef SUBDIRS
 .PRECIOUS: $(SUBDIRS)
+.PHONY: $(SUBDIRS)
+
 $(SUBDIRS):
-	$(SUBDIRS_MAKERULE)
+	@echo "Building $@"
+	$(Q)$(MAKE) $(MAKEOPTS) -q -C $@ || $(MAKE) $(MAKEOPTS) -C $@
 endif
+
+source-link: 
+	@test -z "$$DIR" && DIR="."; \
+	for f in `echo $(SRCFILES) $(SUBDIRS) $(POTHEAD)`; do \
+	    if test -d $$f ; then \
+		mkdir $(TOPDIR)/$(PKG_NAME)-$(PKG_VERSION)/$$DIR/$$f || exit $$?; \
+		$(MAKEF) DIR=$$DIR/$$f -C $$f $@ || exit $$?; \
+	    else \
+		ln $$f $(TOPDIR)/$(PKG_NAME)-$(PKG_VERSION)/$$DIR/$$f || exit $$?; \
+	    fi; \
+	done
 
 #
 # Standard targets
@@ -44,52 +40,68 @@ endif
 
 ifdef LTCOMMAND
 $(LTCOMMAND) : $(SUBDIRS) $(OBJECTS) $(LTDEPENDENCIES)
-	$(LTLINK) -o $@ $(LDFLAGS) $(OBJECTS) $(LDLIBS)
+	@echo "    [LD]     $@"
+	$(Q)$(LTLINK) -o $@ $(LDFLAGS) $(OBJECTS) $(LDLIBS)
 endif
 
 ifdef LTLIBRARY
 $(LTLIBRARY) : $(SUBDIRS) $(LTOBJECTS)
-	$(LTLINK) $(LTLDFLAGS) -o $(LTLIBRARY) $(LTOBJECTS) $(LTLIBS)
+	@echo "    [LD]     $@"
+	$(Q)$(LTLINK) $(LTLDFLAGS) -o $(LTLIBRARY) $(LTOBJECTS) $(LTLIBS)
 
 %.lo: %.c
-	$(LTCOMPILE) -c $<
+	@echo "    [CC]     $@"
+	$(Q)$(LTCOMPILE) -c $<
+else
+%.o: %.c
+	@echo "    [CC]     $@"
+	$(Q)$(CC) $(CFLAGS) -c $<
+
 endif
 
-ifdef LINGUAS
-%.pot: $(XGETTEXTFILES)
-	xgettext --omit-header --language=C --keyword=_ -o $@ $(XGETTEXTFILES)
+ifdef POTHEAD
+$(POTHEAD): $(XGETTEXTFILES)
+	@echo "    [GETTXT] $@"
+	$(Q)$(XGETTEXT) --language=C --keyword=_ --keyword=N_ -o $@ $(XGETTEXTFILES)
 
-%.po:
-	$(MSGMERGE) -o $@.tmpo $@ $(PKG_NAME).pot
-	@if ! diff $@.tmpo $@ >/dev/null; then \
-		echo "$@ is out of date, see $@.tmpo"; \
-	fi
+# Update translations
+update-po: $(POTHEAD) $(wildcard $(TOPDIR)/po/*.po)
+	catalogs="$(wildcard $(TOPDIR)/po/*.po)"; \
+	for cat in $$catalogs; do \
+	  lang=`basename $$cat .po`; \
+	  mv $$lang.po $$lang.old.po; \
+	  echo "$$lang:"; \
+	  if $(MSGMERGE) $$lang.old.po $(POTHEAD) -o $$lang.po; then \
+	    rm -f $$lang.old.po; \
+	  else \
+	    echo "msgmerge for $$lang failed!"; \
+	    rm -f $$lang.po; \
+	    mv $$lang.old.po $$lang.po; \
+	  fi; \
+	done
 
 %.mo: %.po
-	$(MSGFMT) -o $@ $<
+	@echo "    [MSGFMT] $@"
+	$(Q)$(MSGFMT) -c --statistics -o $@ $<
 endif
-
-source :
-	$(SOURCE_MAKERULE)
 
 endif # _BUILDRULES_INCLUDED_
 
 $(_FORCE):
 
-.PHONY : depend
+# dependency build is automatic, relies on gcc -MM to generate.
+.PHONY : depend ltdepend install-qa
 
-depend : $(CFILES) $(HFILES)
-	$(SUBDIRS_MAKERULE)
-	touch .dep
-	$(MAKEDEPEND) -f - -- $(CFLAGS) -- $(CFILES) | \
-	$(SED) -e 's,`pwd`,$(TOPDIR),g' \
-	    -e 's,  */[^ ]*,,g' \
-	    -e '/^[^ ]*: *$$/d' \
-	    -e '/^#.*/d' -e '/^ *$$/d' \
-	> .dep
-	test -s .dep || rm -f .dep
+MAKEDEP := $(MAKEDEPEND) $(CFLAGS)
 
-# Include dep, but only if it exists
-ifeq ($(shell test -f .dep && echo .dep), .dep)
-include .dep
-endif
+ltdepend: .ltdep
+
+.ltdep: $(CFILES) $(HFILES)
+	@echo "    [LTDEP]"
+	$(Q)$(MAKEDEP) $(CFILES) | $(SED) -e 's,^\([^:]*\)\.o,\1.lo,' > .ltdep
+
+depend: .dep
+
+.dep: $(CFILES) $(HFILES)
+	@echo "    [DEP]"
+	$(Q)$(MAKEDEP) $(CFILES) > .dep
